# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_wine_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wine',
            options={'ordering': ('-date_purchased',)},
        ),
        migrations.RenameField(
            model_name='wine',
            old_name='date_consumed',
            new_name='date_opened',
        ),
        migrations.AddField(
            model_name='wine',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='wine_type',
            field=models.CharField(choices=[('Red', 'Red'), ('White', 'White'), ('Ros\xe9', 'Ros\xe9'), ('Orange', 'Orange'), ('Sparkling', 'Sparking'), ('Fortified', 'Fortified'), ('Dessert', 'Desert')], max_length=10, verbose_name='Type'),
        ),
    ]
