# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0005_auto_20160529_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, default='', max_length=50)),
                ('state', localflavor.us.models.USStateField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='wine',
            name='store_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wine.Store'),
        ),
    ]
