# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0007_migrate_store_to_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='store',
        ),
        migrations.RenameField('wine', 'store_fk', 'store',),
    ]
