# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 06:45
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0008_auto_20160529_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='state',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
