# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0011_auto_20160801_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(blank=True, max_length=128, null=True, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, null=True, verbose_name="address cont'd")),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='city')),
                ('zip_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='zip code')),
                ('state', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='winery',
            name='country',
        ),
        migrations.RemoveField(
            model_name='winery',
            name='region',
        ),
        migrations.AddField(
            model_name='winery',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wine.Address'),
        ),
    ]
