# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='winery',
            options={'verbose_name_plural': 'wineries'},
        ),
        migrations.AddField(
            model_name='wine',
            name='wine_type',
            field=models.CharField(default='Red', max_length=10, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
