# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_auto_20160803_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
