# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0004_wine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='etiquette',
            field=models.ImageField(blank=True, null=True, upload_to='wine/'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wine/'),
        ),
    ]
