# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0005_auto_20160804_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='winery',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
