# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0010_auto_20160801_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='importer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='winery',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
