# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 13:23
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0002_zone_max_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='min_temperature',
            field=models.IntegerField(default=15, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(5)]),
        ),
    ]
