# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 13:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0003_zone_min_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='actual_temperature',
            field=models.IntegerField(default=15, validators=[django.core.validators.MaxValueValidator(models.IntegerField(default=15, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(5)])), django.core.validators.MinValueValidator(models.IntegerField(default=15, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(5)]))]),
        ),
    ]
