# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0006_auto_20160801_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.IntegerField()),
                ('col_number', models.IntegerField()),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cellar.Zone')),
            ],
        ),
    ]
