# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0002_auto_20160801_1247'),
        ('cellar', '0007_cell'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='wine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='wine.Wine'),
        ),
    ]
