# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0008_cell_wine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='wine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wine.Wine'),
        ),
    ]
