# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cellar', '0009_auto_20160801_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellar',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
