# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0011_auto_20160802_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellar',
            name='number_of_zones',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cellar',
            name='name',
            field=models.CharField(default='My Cellar', max_length=100),
        ),
    ]
