# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0014_auto_20160803_0602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cell',
            name='wine',
        ),
        migrations.AddField(
            model_name='bottle',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cellar.Cell'),
        ),
    ]
