# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wine', '0003_auto_20160803_0755'),
        ('cellar', '0015_auto_20160803_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='barcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wine.Barcode'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='date_finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='date_opened',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='date_purchased',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='liked_it',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='bottle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='bottle',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wine.Store'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='year',
            field=models.IntegerField(default=2016),
        ),
    ]
