# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-03 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0016_auto_20160803_0755'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='date_added',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='date_purchased',
            field=models.DateField(default=datetime.date(2016, 8, 3)),
        ),
    ]
