# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 07:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0018_auto_20160804_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='date_purchased',
            field=models.DateField(default=datetime.datetime(2016, 8, 5, 7, 28, 12, 233852, tzinfo=utc)),
        ),
    ]
