# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 07:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cellar', '0019_auto_20160805_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottle',
            name='date_purchased',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
